version: "3"
services:
  client:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: client
    depends_on:
      - api
    networks:
      - app-network
  api:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: api
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
